version: "3"
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    ports:
        - "80:80"   
    volumes:
        - /nginx/conf/nginx_default.conf:/etc/nginx/conf.d/default.conf
        - /nginx/client:/var/www
    depends_on:
      - sonarqube
    networks:
      - network_sonar

  sonarqube:
    image: sonarqube:lts-community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonarqube_admin
      SONAR_JDBC_PASSWORD: sonar@Adm1n
    volumes:
      - /sonarqube/sonarqube_data:/opt/sonarqube/data
      - /sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - /sonarqube/sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      network_sonar:
        aliases:
          - sonarqube

  db:
    image: postgres:13
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonarqube_admin
      POSTGRES_PASSWORD: sonar@Adm1n
      POSTGRES_DB: sonarqube
    volumes:
      - /postgresql/:/var/lib/postgresql
      - /postgresql/data:/var/lib/postgresql/data
    networks:
      - network_sonar
  
networks:
  network_sonar:
    driver: bridge